add per grant prize badge for projects
openscilab/openscilab.github.io pull request #15
Opened 2024-06-23 20:08 UTC by F-Shahali

#### Reference Issues/PRs
#14
#### What does this implement/fix? Explain your changes.
- grant prize badge added for projects.

#### Any other comments?
This is the result:
![Screenshot from 2024-06-23 01-16-19](https://github.com/openscilab/openscilab.github.io/assets/49586768/d6e7a987-25b6-4359-abb2-8fc23a4742d9)
![Screenshot from 2024-06-23 01-16-36](https://github.com/openscilab/openscilab.github.io/assets/49586768/e7e76980-9a76-4856-a351-fc6f1eab214b)

2024-06-24 08:11 UTC, AHReccese requested changes
Thank you for your efforts, Take a look at my comments.

2024-06-24 08:11 UTC, AHReccese commented on src/Views/Pages/Home/Sections/Section3/index.tsx
> +		grant: ['PSF Development Grant 2022', 'Nlnet Grant 2022', 'Trelis 2024'],
Trelis AI Grant 2024

2024-06-24 08:11 UTC, AHReccese commented on src/Views/Pages/Home/Sections/Section3/index.tsx
> +		grant: ['PSF 2024'],
PSF Grant 2024

2024-06-25 16:58 UTC, AHReccese reviewed
Thank you for your efforts.
- use `NLnet` instead of Nlnet
- use this structure for PSF grants: PSF Development Grant YEAR
@F-Shahali

2024-06-26 18:01 UTC, AHReccese commented
@F-Shahali 

Also in the mobile mode, show the description after clicking on the badge.
On the desktop mode, it does show the description after hovering the badge, but I think it's better to show it after clicking(and not hovering) too.

In the mobile mode, we should handle the touch event instead, as a way of clicking.

2024-06-26 18:03 UTC, AHReccese commented
@F-Shahali 
There is an urgent issue which I'm going to address after this PR, it would be great if you could handle the feedback ASAP.

Thanks

2024-06-26 21:33 UTC, F-Shahali commented
> @F-Shahali There is an urgent issue which I'm going to address after this PR, it would be great if you could handle the feedback ASAP.
> 
> Thanks

Sure, I will do this within the next one hour.

2024-06-26 22:57 UTC, F-Shahali commented
> @F-Shahali
> 
> Also in the mobile mode, show the description after clicking on the badge. On the desktop mode, it does show the description after hovering the badge, but I think it's better to show it after clicking(and not hovering) too.
> 
> In the mobile mode, we should handle the touch event instead, as a way of clicking.

There is a weird problem with showing the description by clicking in desktop mode. I handled it by hovering and it works now for mobile mode after clicking on the badge.
If you agree, we can have it in this way and after addressing the urgent issue, I will come back to resolve the clicking problem.

2024-06-27 07:27 UTC, AHReccese approved these changes
Thanks for your effort
I agree
LGTM

2024-06-27 07:27 UTC, merged